hw04-Library-SpringJDBC
FlameNur/otus.nuramov.springFramework pull request #4
Opened 2023-01-25 13:01 UTC by FlameNur

2023-05-16 09:20 UTC, Granomir requested changes

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepository bookRepository;
LibraryShellCommands - это по сути класс для взаимодействия с пользаком - чтобы принимать от него команды и возвращать какие то результаты. Вот его основная задача, т.е. в нем должна быть логика только про это. И не должно быть логики про работу непосредсвенно с книгами и т.п. Для работы с книгами нужно сделать еще одну прослойку - сервис, и инжектить его уже в LibraryShellCommands, а сервис внутри себя будет уже иметь BookRepository, с помощью которого взаимодействовать с БД

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        return bookRepository.findById(id).get();
если вызывать get() у пустого optional, то будет эксепшн стандартный, так что тут лучше обработать как-то кейс с ошибкой - например вывести в консоль что книга с таким id не найдена, а не просто стектрейс ошибки в консоль выводить

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +                bookId, bookName, authorId, authorName, genreId, genreName
1) id книги должен генериться при создании книги автоматом в приложении, а не пользак должен его прописывать. А что будет если пользак в запросе пришлет id, который в базе уже есть?
2) ты тут принимаешь еще id и имя авторов и жанров, т.е. у тебя вместе с книгой создаются и авторы и жанры сразу.  Как вариант можно сделать и так, но в таком случае надо делать логично - т.е. если например ты именно хочешь создать новый жанр или автора, то передавать их без id, а если хочешь добавить книгу с сущ. уже в базе автором или жанром, то передавать их с id и в таком случае обновлять сущ. жанры/авторов в базе. Либо оставить возможность создавать книгу только с уже имеющимися в базе жанрами и авторами (которые могут создавать например отдельными командами) и в таком случае в запросе на создание/обновление книги достаточно передавать только их id

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private Book getNewParametersOfBook (long bookId, String bookName,
этот метод надо перенести в сервис

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        bookRepository.update(book);
по хорошему тут сначала надо бы достать из базы эту книгу по id, ато вдруг передали id книги, которого а БД нету вообще? а потом уже обновить её новыми данными. А если не нашлась, то вывести какое-то сообщение в консоль. Но только это тоже в сервисе надо сделать, чтоб он пытался достать, а если не нашел, то выкинуть какой-нить эксепшн, обработку которого делать уже в LibraryShellCommands - вывести сообщение в консоль

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +    public int save(Book book) {
зачем у тебя этот метод что-то возвращает, если результат нигде не исползуется все равно? и тот же вопрос в update

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        } catch (EmptyResultDataAccessException e) {
а в каком случае вылетает EmptyResultDataAccessException? ofNullable же позволяет создать Optional даже если значение будет null? зачем тогда эта обработка ошибок?

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +            if(rs.wasNull()) return null;
если тут возвращаешь null, тогда зачем в первой строчке создаешь new Book() сразу?

2023-05-16 09:20 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +                "UPDATE AUTHOR SET name = :name WHERE id = :id",
а что если переданный id жанра не найден в БД? тогда тут бы бросить тоже эксепшн и обработать его в классе с шеллом. Можно тут в Эксепшн записывать какое-нить сообщение, которое потом и вывести в консоль, достав из эксепшена

2023-05-16 09:21 UTC, Granomir requested changes
нужна доработка

2023-05-16 11:05 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +            if(rs.wasNull()) return null;
Исправил

2023-05-20 07:55 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepository bookRepository;
Исправил

2023-05-26 08:08 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private Book getNewParametersOfBook (long bookId, String bookName,
Исправил

2023-05-26 08:31 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +    public int save(Book book) {
Исправил. Добавил условие для обоих методов

2023-05-26 12:24 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        } catch (EmptyResultDataAccessException e) {
Заменил на Exception, для любого непредвиденного случая) 
Исправил

2023-05-26 13:27 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        return bookRepository.findById(id).get();
Исправил

2023-05-26 13:45 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepository bookRepository;
Исправил

2023-05-29 08:40 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        bookRepository.update(book);
Исправил. Сделал через возвращаемое значение. 1 - обновил, 0 - не обновил

2023-05-29 12:17 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +                "UPDATE AUTHOR SET name = :name WHERE id = :id",
Исправил

2023-05-30 12:32 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +                bookId, bookName, authorId, authorName, genreId, genreName
Исправил частично. Добавил проверку id, оставил возможность прописать id пользаком

2023-05-30 16:30 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepository bookRepository;
+

2023-05-30 16:32 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepository bookRepository;
ok

2023-05-30 17:54 UTC, Granomir requested changes
нужны доработки

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/exceptions/FindByIdException.java
> +public class FindByIdException extends Exception {
свои эксепшены всегда надо наследовать от RuntimeException, чтобы они не требовали принудительную обработку в коде.

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/configs/ApplicationConfiguration.java
> +    public DataSource datasource() {
по-моему это вообще тут необязательно вручную собирать, вроде спринг бут и так собирает сам DataSource, если нашел для него конфиги

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepositoryService bookRepositoryService;
просто BookService можно назвать класс

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        } catch (FindByIdException e) {
если книга не найдена в БД это нормально, не нужно тут выкидывать эксепшн никакой, а просто возвращать null. Эксепшн есть смысл кидать в том случае, когда книгу по id хотят не просто найти, а что-то с ней сделать еще (обновить или удалить например). Про ошибку я тебе писал это про другое - если у тебя findById(id) вернет null, то тут при вызове get() будет ошибка, поэтому тут лучше вообще вместо get() сделать orElse(null)

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +            bookRepositoryService.save(book);
тут не должно быть двух вызовов разных методов bookRepositoryService - это опять получается логика сидит там, где не надо. Вся логика должна быть внутри bookRepositoryService

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    public void updateBook(long bookId, String bookName,
здесь тоже самое, всю логику перенеси в bookRepositoryService. Здесь должен быть только вызов одного метода bookRepositoryService и обработка ошибок, если нужно

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookRepositoryServiceImpl.java
> +        Optional<Book> optionalBook = bookRepository.findById(id);
тут не нужно кидать эксепшн, а если и кидаешь, то тогда зачем метод возвращает Optional<Book>, если он всегда будет кидать ошибку в случае optionalBook.isPresent() == false?

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        Optional<Book> optionalBook = findById(book.getId());
эта проверка должна быть в сервисе. В репозитории не должно быть такой логики - в нем только код, связанный с работой с БД - как достать из БД, сохранить, обнвоить, удалить и т.п.

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        );
сделай как я написал. Либо передаешь id+name и тогда обновляются объекты в БД, либо без id и тогда в БД создаются новые объекты с переданным name

2023-05-30 17:54 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +    public int update(Book book) {
те же самые замечания

2023-05-31 05:56 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/exceptions/FindByIdException.java
> +public class FindByIdException extends Exception {
Исправил

2023-05-31 05:58 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/configs/ApplicationConfiguration.java
> +    public DataSource datasource() {
NamedParameterJdbcOperations без DataSource не работает, просто так бин не получается создать

2023-05-31 06:00 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    private final BookRepositoryService bookRepositoryService;
Исправил

2023-05-31 06:21 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        } catch (FindByIdException e) {
Исправил

2023-05-31 06:30 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookRepositoryServiceImpl.java
> +        Optional<Book> optionalBook = bookRepository.findById(id);
Исправил

2023-05-31 08:49 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +            bookRepositoryService.save(book);
Исправил

2023-05-31 08:49 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +    public void updateBook(long bookId, String bookName,
Исправил

2023-05-31 08:49 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +    public int update(Book book) {
Исправил

2023-06-01 13:11 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        Optional<Book> optionalBook = findById(book.getId());
Исправил

2023-06-01 13:12 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/shellComponent/LibraryShellCommands.java
> +        );
Исправил. Провожу проверку id, если он найден в БД, работаю с ним, если же не найден, то сохраняю

2023-06-01 15:43 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/configs/ApplicationConfiguration.java
> +    public DataSource datasource() {
а если над namedParameterJdbcOperationsBean(DataSource ds) просто поставить @Autowired?

2023-06-01 16:24 UTC, Granomir requested changes
осталось чуток

2023-06-01 16:24 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/configs/ApplicationConfiguration.java
> +    public NamedParameterJdbcOperations namedParameterJdbcOperationsBean(DataSource ds) {
а если над этим методом просто поставить @Autowired?

2023-06-01 16:24 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepository.java
> +    int save(String bookTitle,
а чё ты тут тоже как в update не сделал, чтоб параметром принимался Book? как раз так и надо, сами объекты собирать в сервисе и в репу передавать

2023-06-01 16:24 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +            authorId = getAuthorIdFromDB(authorName);
так нельзя делать - инсерт и потом поиск в базе по имени, чтоб получить id. А что если на этой поле не будет стоять ограничение по уникальности и в базе будет несколько записей с одинаковым именем? Надо чтобы сама операция с инсертом уже сразу возвращала id, или даже вообще весь объект сохраненный. Но ладно тут с этим щас не заморачивайся, потому что в след. домашках с этим будет всё проще намного

2023-06-01 16:24 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookService.java
> +    ) throws BookSaveException;
т.к. эксепшены у тебя теперь от Runtime, то throws тут больше не нужны

2023-06-01 16:24 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookServiceImpl.java
> +        int saveResult = bookRepository.save(bookTitle, authorId, authorName, genreId, genreName);
здесь лучше создать объект Book с полученными данными и передать его на сохранение уже в репу

2023-06-01 16:24 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookServiceImpl.java
> +        Book book = getNewParametersOfBook(bookId, bookTitle, authorId, authorName, genreId, genreName);
а здесь не нужно создавать новый объект книги. Ты же сущ. книгу уже достал из БД, вот этот объект и нужно обновить новыми данными

2023-06-01 17:03 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        if (count != null) return count;
это можно проще записать в виде тернарного оператора

2023-06-02 05:56 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/configs/ApplicationConfiguration.java
> +    public NamedParameterJdbcOperations namedParameterJdbcOperationsBean(DataSource ds) {
Ругается, что нет бина DataSource. Перепробовал разные варианты. 
Если без NamedParameterJdbcOperations работать, Spring и сам может создать бин DataSource, но в моем случаю я не нашел пока как это сделать. В примере, который я смотрел, тоже создавали отдельный бин DataSource.

2023-06-02 06:08 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookService.java
> +    ) throws BookSaveException;
Исправил

2023-06-02 06:22 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepository.java
> +    int save(String bookTitle,
Исправил

2023-06-02 06:22 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookServiceImpl.java
> +        int saveResult = bookRepository.save(bookTitle, authorId, authorName, genreId, genreName);
Исправил

2023-06-02 06:27 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        if (count != null) return count;
Исправил. Совсем забыл про тернарный оператор

2023-06-02 07:11 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/service/BookServiceImpl.java
> +        Book book = getNewParametersOfBook(bookId, bookTitle, authorId, authorName, genreId, genreName);
Исправил

2023-06-02 09:40 UTC, FlameNur commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +            authorId = getAuthorIdFromDB(authorName);
Оставил как есть

2023-06-02 10:57 UTC, Granomir commented on hw04-Library-SpringJDBC/src/main/java/com/nuramov/hw04Library/dao/bookRepository/BookRepositoryImpl.java
> +        if(!authorCheckInDB(book.getAuthor().getId())) {
вот этот код у тя по сути повторяется в save и update, можно было бы вынести просто в отдельный метод saveOrUpdateAuthor() и в нем уже всё это один раз описать. И то же самое с жанром. Ну и еще чё-то можно было бы тут оптимизировать по коду класса этого в целом по мелочи. Но щас уж так оставь, эт просто на будущее - следи чтоб код был без повторений

2023-06-02 12:57 UTC, merged